version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
jobs:
  test:
    docker:
      - image: circleci/node:stretch-browsers
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: Install kubectl
          command: gcloud components install kubectl
      - run:
          name: Set context
          command: gcloud container clusters get-credentials zalenium
      - run:
          name: Get endpoint of zalenium
          command: |
            echo "export WEBDRIVER_HOST=$(kubectl get service zalenium --namespace zalenium -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $BASH_ENV
            echo "export WEBDRIVER_PORT=$(kubectl get service zalenium --namespace zalenium -o jsonpath='{.spec.ports[0].port}')" >> $BASH_ENV
            source $BASH_ENV
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}
            - node-v1
      - run:
          name: npm install
          command: npm ci
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/usr/local/lib/node_modules
      - run:
          name: run tests
          command: npx codeceptjs run-workers 4
      - run:
          name: Generate Report
          command: |
            npx allure-commandline generate output
      - store_artifacts:
          path: allure-report

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
